# Generated by Django 5.0.3 on 2024-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
