# Generated by Django 5.0.3 on 2024-04-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_learner',
            field=models.BooleanField(default=False),
        ),
    ]
