# Generated by Django 5.0.3 on 2024-04-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
